name: siren_py313
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - absl-py
  - attrs
  - backcall
  - blas
  - bleach
  - blinker
  - bzip2
  - c-ares
  - ca-certificates
  - cachetools
  - cairo
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - configargparse
  - cryptography
  - cudatoolkit
  - cycler
  - cytoolz
  - dask-core
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - ffmpeg
  - fftw
  - fontconfig
  - freetype
  - gettext
  - ghostscript
  - giflib
  - glib
  - gmp
  - gnutls
  - google-auth
  - google-auth-oauthlib
  - graphite2
  - graphviz
  - grpcio
  - gst-plugins-base
  - gstreamer
  - h5py
  - harfbuzz
  - hdf5
  - icu
  - idna
  - imageio
  - imagemagick
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jbig
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - kiwisolver
  - ld_impl_linux-64
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libiconv
  - libpng
  - libprotobuf
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libtool
  - libuuid
  - libwebp
  - libxcb
  - libxml2
  - lz4-c
  - markdown
  - markupsafe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbconvert
  - nbformat
  - ncurses
  - nettle
  - networkx
  - ninja
  - notebook
  - numpy
  - numpy-base
  - oauthlib
  - olefile
  - openh264
  - openjpeg
  - openssl
  - pandoc
  - pandocfilters
  - pango
  - parso
  - pcre
  - perl
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkg-config
  - prometheus_client
  - prompt-toolkit
  - protobuf
  - ptyprocess
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pygments
  - pyjwt
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - pywavelets
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - readline
  - requests
  - requests-oauthlib
  - rsa
  - scikit-image
  - scikit-learn
  - scikit-video
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - sqlite
  - tensorboard-plugin-wit
  - terminado
  - testpath
  - tk
  - toolz
  - tornado
  - tqdm
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - widgetsnbextension
  - x264
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxext
  - xorg-libxpm
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - astor
    - cmapy
    - gast
    - google-pasta
    - imageio-ffmpeg
    - imbalanced-learn
    - keras-applications
    - keras-preprocessing
    - matplotlib
    - moviepy
    - opencv-python
    - opt-einsum
    - proglog
    - pytz
    - tensorboard
    - tensorflow
    - tensorflow-estimator
    - termcolor
    - wrapt
    - youtube-dl
  - pytorch
  - torchvision
  - torchaudio
